apiVersion: v1
kind: ConfigMap
metadata:
  name: meta-prom
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
    # Scrapes the endpoint lists for the main Prometheus endpoints
    - job_name: prometheus-endpoints
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      kubernetes_sd_configs:
      - role: endpoints

      relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_service_name]
        regex: prometheus-k8s
      - action: replace
        source_labels: [__meta_kubernetes_service_name]
        target_label: job
