apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: prometheus-meta
  name: prometheus-meta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-meta
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prometheus-meta
        prometheus: meta
    spec:
      containers:
      - image: quay.io/prometheus/prometheus:v1.5.0
        imagePullPolicy: IfNotPresent
        name: prometheus
        resources: {}
        args: ["-config.file=/etc/prometheus/config/prometheus.yaml"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus/config
      volumes:
      - name: config-volume
        configMap:
          name: meta-prom
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      nodeSelector:
        isolation: none
