metadata:
  name: prometheus
spec:
  associatePublicIp: true
  machineType: c3.2xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    isolation: prometheus
  role: Node
  rootVolumeType: gp2
  zones:
  - eu-west-1a
