metadata:
  name: nodes
spec:
  associatePublicIp: true
  machineType: ${WORKER_MACHINE_TYPE}
  maxSize: ${NUM_WORKERS}
  minSize: ${NUM_WORKERS}
  nodeLabels:
    isolation: none
  role: Node
  zones:
  - ${AWS_REGION}a
