metadata:
  name: nodes
spec:
  associatePublicIp: true
  image: kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    isolation: none
  role: Node
  zones:
  - eu-west-1a
